apiVersion: apps/v1
kind: Deployment
metadata:
   name: migration-deploy
   labels:
      app: migration
      env: dev
      owner: DmitryAvdonin
spec:
   replicas: 1
   selector:
      matchLabels:
         project: adv
   template:
      metadata:
         labels:
            project: adv
      spec:
         containers:
            - name: migration
              image: dmitryavdonin/migrate:latest
              envFrom:
                 - secretRef:
                      name: postgres-secret